package Server;

public enum ServerCommands {
    DISCONNECT,
    GET_MAPS,
    INIT,
    INIT_DONE,
    RECEIVING_CHAT,
    SENDING_CHAT,
    SENDING_PRIVATE_MAP,
    SENDING_SAVE,
    SHARING_MAP,
    START_RECEIVING_PUBLIC,
    STOP_RECEIVING_PUBLIC
}
